name: Trigger plugin-pb-go code generation
on:
  push:
    branches:
      - main

jobs:
  trigger-gen:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          app-id: ${{ secrets.CQ_APP_ID }}
          private-key: ${{ secrets.CQ_APP_PRIVATE_KEY }}
          permission-actions: write
          repositories: |
            plugin-pb-go
            plugin-pb-python
            plugin-pb-java
            plugin-pb-javascript
      - name: Trigger plugin-pb-go code generation
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'cloudquery',
              repo: 'plugin-pb-go',
              workflow_id: 'regen.yml',
              ref: 'main',
            })
      - name: Trigger plugin-pb-python code generation
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'cloudquery',
              repo: 'plugin-pb-python',
              workflow_id: 'regen.yml',
              ref: 'main',
            })
      - name: Trigger plugin-pb-java code generation
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'cloudquery',
              repo: 'plugin-pb-java',
              workflow_id: 'regen.yml',
              ref: 'main',
            })
      - name: Trigger plugin-pb-javascript code generation
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'cloudquery',
              repo: 'plugin-pb-javascript',
              workflow_id: 'regen.yml',
              ref: 'main',
            })
